[profile.default]
auto_detect_solc = true
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
ignored_warnings_from = ["lib/token-bridge-contracts/contracts/tokenbridge/libraries/Cloneable.sol",
"lib/nitro-contracts/test/foundry/AbsInbox.t.sol", "lib/token-bridge-contracts/contracts/tokenbridge/libraries/gateway/GatewayRouter.sol"]
match-path = 'test/unit/**/*.sol'
ffi = true
solc_version = "0.8.24"

[profile.fork]
match-path = 'test/fork/**/*.sol'
evm_version = 'shanghai'

[rpc_endpoints]
kinto = "${KINTO_RPC_URL}"
mainnet = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
kinto_devnet = "${TEST_KINTO_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
arbitrum = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
base = { key = "${ETHERSCAN_BASE_KEY}" }
optimism = { key = "${ETHERSCAN_OPTIMISM_KEY}" }

[fuzz]
runs = 16
